spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: sb10-MoPl-team3

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:mopl}
    username: ${POSTGRES_USER:mopl}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1h}
  issuer: ${JWT_ISSUER:mopl}