spring:
  jpa:
    properties:
      hibernate:
        format_sql: false

auth:
  refresh-token-cookie:
    secure: ${REFRESH_TOKEN_COOKIE_SECURE:true}
  password-reset-mail:
    mode: ${PASSWORD_RESET_MAIL_MODE:smtp}
