spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_API_KEY}"
        password="${KAFKA_API_SECRET}";
      ssl.endpoint.identification.algorithm: https

  jpa:
    properties:
      hibernate:
        format_sql: false

auth:
  refresh-token-cookie:
    secure: ${REFRESH_TOKEN_COOKIE_SECURE:true}
  password-reset-mail:
    mode: ${PASSWORD_RESET_MAIL_MODE:smtp}
