auth:
  refresh-token-cookie:
    secure: ${REFRESH_TOKEN_COOKIE_SECURE:false}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,caches,metrics
  health:
    mail:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    org.apache.kafka: ERROR
    org.apache.kafka.clients.NetworkClient: OFF
